/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-06-02 16:42:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"MyStyle.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- carousel Slider AutoPlay-->\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"w3-container w3-Gray\">\r\n");
      out.write("   \r\n");
      out.write("<div class=\"w3-container\">\r\n");
      out.write("<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("\t<div class=\"carousel-inner\" style=\"height:300px;\">\r\n");
      out.write("      <div class=\"item active\">\r\n");
      out.write(" \t  <img src=\"./resources/image/phone1.jpg\" style=\"width:100%;height:300px;\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"item\">\r\n");
      out.write(" \t\t <img src=\"./resources/image/phone2.jpg\" style=\"width:100%;height:300px;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"item\">\r\n");
      out.write(" \t\t <img src=\"./resources/image/phone3.jpg\" style=\"width:100%;height:300px;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"item\">\r\n");
      out.write(" \t\t <img src=\"./resources/image/phone4.jpg\" style=\"width:100%;height:300px;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"item\">\r\n");
      out.write(" \t\t <img src=\"./resources/image/phone5.jpg\" style=\"width:100%;height:300px;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Next</span>\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<hr>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-md-4\"><div class=\"thumbnail\">\r\n");
      out.write("\t<a href=\"\"><img height=\"120px\" width=\"253px\" src=\"./resources/image/phone2.jpg\"></img></a>\r\n");
      out.write("\t<div class=\"caption\"><center><h3>Apple 4s </h3><p>Rs.50000</p></center>\r\n");
      out.write("\t<a class=\"btn\" href=\"proDescription\">Buy Now</a></div></div></div>\r\n");
      out.write("\t<div class=\"col-md-4\"><div class=\"thumbnail\">\r\n");
      out.write("\t<a href=\"\"><img height=\"120px\" width=\"253px\" src=\"./resources/image/phone3.jpg\"></img></a>\r\n");
      out.write("\t<div class=\"caption\"><center><h3>Moto</h3><p>Rs.12750</p></center>\r\n");
      out.write("\t<a class=\"btn\" href=\"proDescription\">Buy Now</a></div></div></div>\r\n");
      out.write("\t<div class=\"col-md-4\"><div class=\"thumbnail\">\r\n");
      out.write("\t<a href=\"\"><img height=\"120px\" width=\"253px\" src=\"./resources/image/phone4.jpg\"></img></a>\r\n");
      out.write("\t<div class=\"caption\"><center><h3>Oppo A37</h3><p>Rs.10750</p></center>\r\n");
      out.write("\t<a class=\"btn\" href=\"proDescription\">Buy Now</a></div></div></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<hr>\t\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-md-4\"><div class=\"thumbnail\">\r\n");
      out.write("\t<a href=\"\"><img height=\"120px\" width=\"253px\" src=\"./resources/image/phone7.jpg\"></img></a>\r\n");
      out.write("\t<div class=\"caption\"><center><h3>Hitachi</h3><p>Rs.10500</p></center>\r\n");
      out.write("\t<a class=\"btn\" href=\"proDescription\">Buy Now</a></div></div></div>\r\n");
      out.write("\t<div class=\"col-md-4\"><div class=\"thumbnail\">\r\n");
      out.write("\t<a href=\"\"><img height=\"120px\" width=\"253px\" src=\"./resources/image/phone3.jpg\"></img></a>\r\n");
      out.write("\t<div class=\"caption\"><center><h3>Men Shoe Dark Grey </h3><p>Rs.2750</p></center>\r\n");
      out.write("\t<a class=\"btn\" href=\"proDescription\">Buy Now</a></div></div></div>\r\n");
      out.write("\t<div class=\"col-md-4\"><div class=\"thumbnail\">\r\n");
      out.write("\t<a href=\"\"><img height=\"120px\" width=\"253px\" src=\"./resources/image/phone5.jpg\"></img></a>\r\n");
      out.write("\t<div class=\"caption\"><center><h3>Samsung Galaxy 5s </h3><p>Rs.2750</p></center>\r\n");
      out.write("\t<a class=\"btn\" href=\"proDescription\">Buy Now</a></div></div></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<hr>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var myIndex = 0;\r\n");
      out.write("carousel();\r\n");
      out.write("\r\n");
      out.write("function carousel() {\r\n");
      out.write("  \t$('#myCarousel').carousel({\r\n");
      out.write("\t    interval: 1200\r\n");
      out.write("\t});\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("//This is for Search Box\r\n");
      out.write("$(document).ready(function(e){\r\n");
      out.write("    $('.search-panel .dropdown-menu').find('a').click(function(e) {\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tvar param = $(this).attr(\"href\").replace(\"#\",\"\");\r\n");
      out.write("\t\tvar concept = $(this).text();\r\n");
      out.write("\t\t$('.search-panel span#search_concept').text(concept);\r\n");
      out.write("\t\t$('.input-group #search_param').val(param);\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
