/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-06-07 06:26:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customerdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>ShaMobile Store</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("    background-color: #525252;\r\n");
      out.write("}\r\n");
      out.write(".centered-form{\r\n");
      out.write("\tmargin-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".centered-form .panel{\r\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.8);\r\n");
      out.write("\tbox-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("        <div class=\"row centered-form\">\r\n");
      out.write("        <div class=\"col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4\">\r\n");
      out.write("        \t<div class=\"panel panel-default\">\r\n");
      out.write("        \t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t    \t\t<h3 class=\"panel-title\">SHIPPING DETAILS<small>Enter</small></h3>\r\n");
      out.write("\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t \t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t    \t\t<form  action=\"summaryDetails\">\r\n");
      out.write("\t\t\t    \t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t    \t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-6\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                <input type=\"text\" name=\"name\" id=\"first_name\" class=\"form-control input-sm\" placeholder=\"First Name\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t\t    \t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-6\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t\t<input type=\"text\" name=\"email\" id=\"email\" class=\"form-control input-sm\" placeholder=\"Email\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t\t    \t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t    \t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t\t\t\t<input type=\"text\" name=\"phone\" id=\"Phone\" class=\"form-control input-sm\" placeholder=\"phone\">\r\n");
      out.write("\t\t\t    \t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t    \t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-6\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t<input type=\"textarea\" name=\"textarea\" id=\"textarea\" class=\"form-control input-sm\" placeholder=\"address\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<div class=\"col-xs-6 col-sm-6 col-md-6\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t\t<input type=\"date\" id=\"myDate\" name=\"date\" value=\"2017-06-02\" class=\"form-control input-sm\" placeholder=\"\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t\t\r\n");
      out.write("\t\t\t\t    \t\t\t<input type=\"submit\" value=\"DETAILS\" class=\"btn btn-info btn-block\">\r\n");
      out.write("\t\t\t\t    \t\t\r\n");
      out.write("\t\t\t\t    \t\t</form>\r\n");
      out.write("\t\t\t    \t</div>\r\n");
      out.write("\t    \t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
